### ISSUE TITLE
shaper range switch

### ISSUE THREAD

**Issue by alto777** [mhetrick/hetrickcv#14]
hi Michael!

I was using AS's rework of your Shaper and got confused by its behaviour. In case he bungled it somehow I figured to try yours before deciding to be confused.

Specifically what is the function of the Range switch? It does not seem to simply effect the magnitude of the output (shaped) wave, viz:

In the +5/-5 position, everything works like common sense would predict.

In the +10/-10 position the Shape knob does not produce "needles" when fully CCW, rather it reduces the amplitude of the output waveform to zero.

(The CV Amount attenuvertor control has only the effect of the Shape knob, that is it functions the same way depending on the Range selected.)

So I've decided to be confused and ask for your help/explanation. Thanks!

alto777

**Comment by mhetrick** [comment]
Yeah, it's a bit confusing! This is to deal with the lack of standards in Euro and VCV. Most oscillators produce in the range of +/- 5V. However, there are a few that go louder. As an example, Rings, Braids, and Elements can all get extremely loud depending on the settings.

For most purposes, the +/- 5 V range will give the expected behavior, but it will have the side effect of clipping the incoming audio if it exceeds the given range.

The CCW silence makes sense if your signal is not full-range. The best way to think about this shaper is as a magnet. At CW settings, the magnets are placed at the top and bottom extremes of the waveform, so it pulls the audio toward those extremes and creates squares at intense settings. At CCW, the magnet is placed at 0.0, so the audio is pulled to silence. The only audio that can escape the magnet is audio that is close to the maximum range.

**Comment by alto777** [comment]
{sound of hand slapping forehead}

Of course that makes perfect sense now that you 'splain it to me. I'm still getting to know the expected voltages in synthesizer world.

While I have your attention (!) let me say I have been making good sounds with your modules. I like your doc style, too - "Patch Ideas" is something I will def ~~steal~~ borrow one day…

ASR wired patch-idea style is an instant winner.

I wired up a bunch of your Flip Flops and gates and got a little FSM working very well except the F/Fs do not save state with the JSON mechanism. I know, picky picky. I only just figured out why half the settings on my stuff seemed to get remembered and the rest did not. I don't inamgine you'd have to blindly hack the JSON in/out overrides like I did. Got lucky, everything seems to work. It frightens me to consider how far I have gotten without really knowing what I am doing.

I may use the Flip Flop idea, I've drawn a Hetrick F/F in 2U by stacking the T and D jacks and losing the (mostly) redundant lamps. Reminds me of the old days when flip-flops came a few to a card and any digital prototype ona rack needed dozens of cards. Yeah, I'm old.

Fun! THX.

**Comment by mhetrick** [comment]
No problem! Yeah, the states *should* be saving, but I need to rewrite from JSON bool to JSON int to fix that. Bools used to work for that, but were changed in 0.6. The Unfiltered modules have the same issue... I'll get to that soon.

Feel free to reuse any of my code. The FF here is partially inspired by the Intellijel Plog, which has a stacked T and D FFs. The Intellijel Flip Flop itself (now discontinued) is also very cool, but fairly similar in nature. Another FF type that would be useful is a C-Element. I was going to add it to this FF, but I can't remember what stopped me.

**Comment by alto777** [comment]
Thank you for your rapid and kind reply.  Intellijel objs, cool, I like spending, er, somewhat less than $220 per copy for some gates and f/fs. Part of me still wants a "real" synthesizer.

I'll file the C-Element under "ya learn something every day". Inchestin'. Can't see it in a patch, but that's just testament to my lack of imagination.
